services:
  - type: web
    name: cultists-game
    language: python  # This line was changed from "env: python"
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 server:app"
